/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/java.glb -T 
Files: public/models/java.glb [10.58MB] > C:\Prog\Magan\threejs-portfolio\java-transformed.glb [321.39KB] (97%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/java-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.mesh_0.geometry} material={materials['Default Material']} />
    </group>
  )
}

useGLTF.preload('/java-transformed.glb')
